import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  modalRoot: {
    flex: 1,
    backgroundColor: '#52aebc50',
    // backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    // marginBottom: 10,
  },
  modalTitle: {
    fontWeight: 'bold',
    fontSize: 30,
    marginVertical: 10,
  },
  modalButtonContainer: {
    backgroundColor: '#ffffff',
    paddingHorizontal: '5%',
    // paddingBottom: 60,
    // paddingTop: 5,
    alignItems: 'center',
    // margin: 60,
    // opacity: 1,
    height: '40%',
    borderRadius: 15,
  },
  // googleButton: {
  //   width: 192,
  //   height: 48,
  // },
  googlePress: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderColor: 'grey',
    borderRadius: 5,
    borderWidth: 1,
    padding: 10,
    marginTop: 15,
    marginBottom: 5,
    width: 200,
  },
  googleLogo: {
    height: 25,
    width: 25,
  },
  googleText: {
    color: '#606060',
    paddingHorizontal: 10,
    fontWeight: 'bold',
  },
  facebookPress: {
    backgroundColor: '#3c5c9c',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#3b5998',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 10,
    marginVertical: 5,
    width: 200,
  },
  facebookText: {
    color: 'white',
    fontWeight: 'bold',
  },
  applePress: {
    backgroundColor: 'black',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: 'black',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    width: 200,
    marginVertical: 5,
  },
  appleText: {
    paddingHorizontal: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  hostedUIPress: {
    // backgroundColor: '#52aebc',
    // borderWidth: 1,
    // borderRadius: 5,
    // borderColor: 'black',
    // flexDirection: 'row',
    // padding: 10,
    // marginVertical: 5,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderColor: 'grey',
    borderRadius: 5,
    borderWidth: 1,
    padding: 10,
    // marginTop: 15,
    marginVertical: 5,
    width: 200,
  },
  mhmLogo: {
    height: 25,
    width: 45,
  },
  hostedUIText: {
    // paddingHorizontal: 12,
    // fontWeight: 'bold',
    // color: 'black',
    color: '#606060',
    paddingHorizontal: 10,
    fontWeight: 'bold',
  },
  // appleButtonContainer: {
  //   flex: 1,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   backgroundColor: 'white',
  // },
  // appleBtn: {height: 44, width: 200},
});

export default styles;
